#########################################################################################
#                                 PROFESSOR DOCUMENTATION
# Author: Erick Muuo
# Copyright (c) 2026 Open Crafts Interactive. All Rights Reserved.
# Documentation for mkdocs: https://squidfunk.github.io/mkdocs-material/getting-started/
#
#########################################################################################

site_name: Professor Docs
site_url: https://opencrafts-io.github.io/verisafe/
theme:
  features:
    - header.autohide
    - navigation.footer
  name: material
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

        # Palette toggle for dark mode
    - scheme: slate
      primary: light blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Google Sans
    code: Google Sans Code

copyright: Copyright &copy; 2025 Open Crafts Interactive Ltd
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/opencrafts-io
      name: Github


    - icon: fontawesome/solid/paper-plane
      link: mailto:developers@opencrafts.io
      name: Email

    
